site_name: Baseprints
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - attr_list
  - admonition
nav:
  - Baseprints:
    - index.md
    - Authoring: author.md
  - Basecast:
    - basecast/index.md
    - Usage: basecast/usage.md
    - Containers: basecast/containers.md
    - Package Install: basecast/install.md
