site_name: Baseprints
site_url: https://baseprints.singlesource.pub/
repo_name: github<br>singlesourcepub/baseprints
repo_url: https://github.com/singlesourcepub/baseprints
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: theme
  features:
    - content.action.edit
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
#  - tables
nav:
  - Interoperability Forum: index.md
  - Baseprint Document Format:
    - bdf/index.md
    - jats.md
  - Document Successions: successions.md
  - About: about.md
extra:
  generator: false
copyright: '<a href="/about/">About</a>'
watch:
  - docs
  - theme
