site_name: Baseprints
site_url: https://baseprints.singlesource.pub/
theme:
  name: material
  custom_dir: theme
  features:
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
markdown_extensions:
  - attr_list
  - admonition
nav:
  - Baseprints:
    - index.md
    - tech.md
watch:
  - docs
  - theme
